"""empty message

Revision ID: 297dbb447ed1
Revises: None
Create Date: 2015-11-02 11:04:36.632349

"""

# revision identifiers, used by Alembic.
revision = '297dbb447ed1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarm', sa.Column('state', sa.Boolean(), nullable=True))
    op.drop_column('users', 'music_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('music_id', sa.INTEGER(), nullable=True))
    op.drop_column('alarm', 'state')
    ### end Alembic commands ###
